version: "2"

services:

  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DATABASE: dev
    volumes:
      - database:/bitnami/postgresql
    networks:
      - challenge

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - cache:/bitnami/redis
    networks:
      - challenge

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - challenge
  
  adminer:
    image: 'adminer'
    ports:
      - "5050:8080"
    networks:
      - challenge
  
volumes:
  database:
  cache:

networks:
  challenge:
    driver: bridge